#!/usr/bin/env python3
"""Bake a per-CD-sector loudness envelope of the soundtrack into a C header.

The demo indexes this table by the CD's playback position (CdlGetlocP), so the
SecKC skull pulses in sync with the music with ZERO runtime audio reads — none
of the per-frame SpuRead that used to crater the framerate.

  music_loop.wav  ->  vu_env.h   (one byte per 1/75s sector, 0..255)
"""
import wave
import numpy as np

SRC = "music_loop.wav"
DST = "vu_env.h"
SECTOR_HZ = 75                      # CD audio sectors per second (CdlGetlocP unit)

w = wave.open(SRC, "rb")
ch, sw, sr, n = w.getnchannels(), w.getsampwidth(), w.getframerate(), w.getnframes()
a = np.frombuffer(w.readframes(n), dtype="<i2").astype(np.float32).reshape(-1, ch)
w.close()
mono = a.mean(axis=1)

spp = sr // SECTOR_HZ               # samples per sector (e.g. 588 @44.1k)
nsec = len(mono) // spp
peak = np.empty(nsec, np.float32)
for i in range(nsec):
    seg = mono[i * spp:(i + 1) * spp]
    peak[i] = np.abs(seg).max()

# VU feel: instant attack, smooth decay
env = np.zeros(nsec, np.float32)
e = 0.0
for i in range(nsec):
    e = max(peak[i], e * 0.90)
    env[i] = e

env /= max(env.max(), 1.0)          # normalise 0..1
vu = np.clip(env * 255.0, 0, 255).astype(np.uint8)

with open(DST, "w") as f:
    f.write("/* Generated by tools/make_vu.py from music_loop.wav. Per-CD-sector\n")
    f.write(" * (1/75s) loudness envelope, indexed by CdlGetlocP playback position. */\n")
    f.write(f"#define VU_ENV_LEN {len(vu)}\n")
    f.write("static const unsigned char vu_env[VU_ENV_LEN] = {\n")
    for i in range(0, len(vu), 16):
        f.write("\t" + ",".join(str(int(x)) for x in vu[i:i + 16]) + ",\n")
    f.write("};\n")
print(f"wrote {DST}: {len(vu)} sectors ({len(vu)/SECTOR_HZ:.1f}s)")
